// Mumbai Suburban Trans-Harbour Sunday Mega Block Datasets for PostgreSQL Seeding

export const corridorsData = [
  {
    id: 'COR-THN-VSH',
    name: 'THN–VSH',
    from: 'Thane',
    to: 'Vashi (Trans-Harbour)',
    totalKm: 18.5,
    availableHours: 5.0,
    trainDensity: 'High',
    plannedBlocks: 3,
    availableCapacity: 75,
    risk: 'High',
    timeSlots: [
      { startHour: 0, endHour: 4, type: 'available', label: 'Night Maintenance Window' },
      { startHour: 4, endHour: 7, type: 'train-occupied', label: 'Early Local Trains' },
      { startHour: 7, endHour: 11, type: 'train-occupied', label: 'Morning Peak Hour Locals (3m headway)' },
      { startHour: 11, endHour: 16, type: 'maintenance', label: 'Sunday Mega Block (11:05-16:05)' },
      { startHour: 16, endHour: 21, type: 'train-occupied', label: 'Evening Peak Hour Locals' },
      { startHour: 21, endHour: 23.5, type: 'train-occupied', label: 'Night Local Services' },
      { startHour: 23.5, endHour: 24, type: 'available', label: 'Night Margin' },
    ],
  },
  {
    id: 'COR-THN-PNVL',
    name: 'THN–PNVL',
    from: 'Thane',
    to: 'Panvel (Trans-Harbour)',
    totalKm: 38.0,
    availableHours: 4.5,
    trainDensity: 'High',
    plannedBlocks: 2,
    availableCapacity: 68,
    risk: 'Medium',
    timeSlots: [
      { startHour: 0, endHour: 3.5, type: 'available' },
      { startHour: 3.5, endHour: 7, type: 'train-occupied' },
      { startHour: 7, endHour: 11, type: 'train-occupied' },
      { startHour: 11, endHour: 15.5, type: 'maintenance', label: 'Mega Block Window (Turbhe-Panvel)' },
      { startHour: 15.5, endHour: 21.5, type: 'train-occupied' },
      { startHour: 21.5, endHour: 24, type: 'available' },
    ],
  },
  {
    id: 'COR-CSMT-PNVL',
    name: 'CSMT–PNVL',
    from: 'CSMT',
    to: 'Panvel (Harbour Line)',
    totalKm: 49.0,
    availableHours: 5.2,
    trainDensity: 'High',
    plannedBlocks: 4,
    availableCapacity: 72,
    risk: 'High',
    timeSlots: [
      { startHour: 0, endHour: 4, type: 'available' },
      { startHour: 4, endHour: 11, type: 'train-occupied' },
      { startHour: 11, endHour: 16, type: 'maintenance', label: 'Harbour Sunday Mega Block' },
      { startHour: 16, endHour: 22, type: 'train-occupied' },
      { startHour: 22, endHour: 24, type: 'available' },
    ],
  },
];

export const maintenanceTasksData = [
  {
    id: 'TRK-MH-201',
    department: 'Engineering',
    asset: 'Rail Joint & Switch Expansion',
    assetType: 'Track',
    location: 'Km 7/4–8/2 (Rabale–Kopar Khairane)',
    kmFrom: 7.4,
    kmTo: 8.2,
    corridor: 'THN–VSH',
    issue: 'Rail flaw detected by Ultrasonic Flaw Detector (USFD) on Trans-Harbour Up Line',
    maintenanceType: 'Corrective Rail Replacement',
    criticality: 'Critical',
    priority: 'P1',
    priorityScore: 98,
    dueDate: '2026-09-06',
    estimatedDuration: 180,
    status: 'Recommended',
    recommendedBlock: '06 Sep · 11:05–16:05 (Sunday Mega Block)',
    safetyImpact: 5,
    failureRisk: 0.88,
    overdueDays: 0,
  },
  {
    id: 'SIG-MH-405',
    department: 'S&T',
    asset: 'Digital Axle Counter (DAC)',
    assetType: 'Signalling',
    location: 'Km 12/0 (Turbhe Junction Yard)',
    kmFrom: 12.0,
    kmTo: 12.0,
    corridor: 'THN–VSH',
    issue: 'Intermittent track circuit failure on Turbhe Yard crossover line 4',
    maintenanceType: 'Point & Signal Interlocking Test',
    criticality: 'High',
    priority: 'P1',
    priorityScore: 92,
    dueDate: '2026-09-06',
    estimatedDuration: 120,
    status: 'Recommended',
    recommendedBlock: '06 Sep · 11:05–16:05 (Sunday Mega Block)',
    safetyImpact: 4,
    failureRisk: 0.74,
    overdueDays: 0,
  },
  {
    id: 'TD-MH-802',
    department: 'Traction',
    asset: 'OHE Catenary Wire & Insulator',
    assetType: 'Traction / OHE',
    location: 'Km 4/0–6/5 (Airoli–Ghansoli)',
    kmFrom: 4.0,
    kmTo: 6.5,
    corridor: 'THN–VSH',
    issue: 'Contact wire height adjustment & insulator washing (25kV AC OHE)',
    maintenanceType: 'Preventive Overhaul',
    criticality: 'High',
    priority: 'P2',
    priorityScore: 86,
    dueDate: '2026-09-06',
    estimatedDuration: 150,
    status: 'Recommended',
    recommendedBlock: '06 Sep · 11:05–16:05 (Sunday Mega Block)',
    safetyImpact: 4,
    failureRisk: 0.62,
    overdueDays: 0,
  },
  {
    id: 'TRK-MH-208',
    department: 'Engineering',
    asset: 'Turnout 14B Point Machine',
    assetType: 'Track / Switch',
    location: 'Km 18/2 (Vashi Station Yard)',
    kmFrom: 18.2,
    kmTo: 18.2,
    corridor: 'THN–VSH',
    issue: 'Sleeper spacing & ballast packing required at Vashi Trans-Harbour crossover',
    maintenanceType: 'Heavy Tamping (CSM Tamping Machine)',
    criticality: 'High',
    priority: 'P2',
    priorityScore: 84,
    dueDate: '2026-09-06',
    estimatedDuration: 150,
    status: 'Pending',
    safetyImpact: 4,
    failureRisk: 0.58,
    overdueDays: 0,
  },
];

export const maintenanceBlocksData = [
  {
    id: 'MB-THN-501',
    date: '2026-09-06',
    startTime: '11:05',
    endTime: '16:05',
    corridor: 'THN–VSH',
    kmFrom: 4.0,
    kmTo: 18.2,
    departments: ['Engineering', 'S&T', 'Traction'],
    tasks: ['TRK-MH-201', 'SIG-MH-405', 'TD-MH-802', 'TRK-MH-208'],
    status: 'Planned',
    isCoordinated: true,
    suitabilityScore: 96,
    trainImpact: 'Medium',
  },
  {
    id: 'MB-THN-502',
    date: '2026-09-06',
    startTime: '11:30',
    endTime: '15:30',
    corridor: 'THN–PNVL',
    kmFrom: 11.5,
    kmTo: 28.0,
    departments: ['Engineering', 'Traction'],
    tasks: ['TD-MH-810'],
    status: 'Planned',
    isCoordinated: true,
    suitabilityScore: 90,
    trainImpact: 'Medium',
  },
];

export const conflictsData = [
  {
    id: 'C-MH-101',
    severity: 'High',
    description: 'Trans-Harbour Sunday Mega Block overlaps with scheduled JNPT Container Freight Train #JNPT-9042',
    location: 'THN–VSH (Turbhe Yard)',
    kmRange: 'Km 11.5–13.0',
    currentBlock: '06 Sep (Sunday) · 11:05–16:05',
    conflictWith: 'JNPT Port Container Freight Train #JNPT-9042 (Scheduled 13:15)',
    conflictTime: '13:15',
    aiSolution: 'Divert freight train #JNPT-9042 via Kopar-Kalamboli goods bypass line during Mega Block hours',
    expectedImpact: 'Zero disruption to Trans-Harbour Mega Block, 0m freight delay',
    impactReduction: 100,
    status: 'Open',
    relatedBlockId: 'MB-THN-501',
  },
];

export const aiRecommendationsData = [
  {
    id: 'REC-MH-001',
    blockId: 'MB-THN-501',
    date: '06 Sep 2026 (Sunday)',
    suggestedTime: '11:05–16:05',
    timeWindow: '11:05–16:05',
    durationMinutes: 300,
    corridor: 'THN–VSH',
    tasks: maintenanceTasksData,
    isCoordinated: true,
    suitabilityScore: 96,
    trainImpact: 'Medium',
    efficiencyGain: 'Sunday passenger volume is 48% lower; saves 5.5 hours track closure time vs separate blocks',
    trainsAffected: 12,
    downtimeSavedMinutes: 330,
    conflictAvoided: 'Avoided weekday peak commuter rush (3m headway); diverted JNPT container freight via Kopar bypass',
    explanation: 'Trans-Harbour Sunday Mega Block proposal: Consolidates Rail flaw replacement (Rabale–Kopar Khairane), Digital Axle Counter testing (Turbhe Yard), OHE Insulator Washing (Airoli–Ghansoli), and Turnout Tamping (Vashi Yard) into a single 5-hour shadow possession.',
    status: 'Pending',
    reasons: [
      'Sunday passenger commuter traffic drops by 48% on Trans-Harbour section',
      'Combines 4 critical maintenance tasks across Engineering, S&T, and Traction into 1 shadow block',
      'Freight train #JNPT-9042 easily diverted via Kopar-Kalamboli goods bypass line',
    ],
    assetAvailability: 5.2,
    trainDisruption: 'Medium',
    tasksConsolidated: 4,
    departments: ['Engineering', 'S&T', 'Traction'],
    scoreBreakdown: {
      maintenanceUrgency: { score: 25, max: 25 },
      assetCriticality: { score: 24, max: 25 },
      trainTrafficImpact: { score: 22, max: 25 },
      multiDeptCoordination: { score: 15, max: 15 },
      historicalEfficiency: { score: 10, max: 10 },
    },
  },
];

export const systemIntegrationsData = [
  {
    id: 'SYS-CR-TMS',
    name: 'CR-TMS',
    fullName: 'Central Railway Track Management System',
    department: 'Engineering (Track)',
    endpoint: 'api.cr.tms.indianrail.gov.in/mumbai-suburban/defects',
    status: 'Connected',
    lastSync: '30 Aug 2026 · 00:05',
    recordsCount: 14205,
    description: 'Ultrasonic track defect logs, turnout wear, ballast profiles for Mumbai Suburban division',
  },
  {
    id: 'SYS-CR-SMMS',
    name: 'CR-SMMS',
    fullName: 'Central Railway Signal & Telecom Management',
    department: 'S&T',
    endpoint: 'api.cr.smms.indianrail.gov.in/suburban-axle-counters',
    status: 'Connected',
    lastSync: '30 Aug 2026 · 00:08',
    recordsCount: 9410,
    description: 'Digital Axle Counters, point machine health logs, automatic signal logs for Trans-Harbour line',
  },
];
