// Central Railway Mumbai Suburban Infrastructure Master Definitions

export const corridorsData = [
  {
    id: 'COR-THN-VSH',
    name: 'THN–VSH',
    from: 'Thane',
    to: 'Vashi (Trans-Harbour)',
    totalKm: 18.5,
    availableHours: 5.0,
    trainDensity: 'High',
    plannedBlocks: 0,
    availableCapacity: 85,
    risk: 'Medium',
    timeSlots: [
      { startHour: 0, endHour: 4, type: 'available', label: 'Night Maintenance Margin' },
      { startHour: 4, endHour: 7, type: 'train-occupied', label: 'Early Local Trains' },
      { startHour: 7, endHour: 11, type: 'train-occupied', label: 'Morning Peak Hour Locals (3m headway)' },
      { startHour: 11, endHour: 16, type: 'maintenance', label: 'Sunday Mega Block Possessions' },
      { startHour: 16, endHour: 21, type: 'train-occupied', label: 'Evening Peak Hour Locals' },
      { startHour: 21, endHour: 23.5, type: 'train-occupied', label: 'Night Services' },
      { startHour: 23.5, endHour: 24, type: 'available', label: 'Night Margin' },
    ],
  },
  {
    id: 'COR-THN-PNVL',
    name: 'THN–PNVL',
    from: 'Thane',
    to: 'Panvel (Trans-Harbour)',
    totalKm: 38.0,
    availableHours: 4.5,
    trainDensity: 'High',
    plannedBlocks: 0,
    availableCapacity: 80,
    risk: 'Medium',
    timeSlots: [
      { startHour: 0, endHour: 3.5, type: 'available' },
      { startHour: 3.5, endHour: 7, type: 'train-occupied' },
      { startHour: 7, endHour: 11, type: 'train-occupied' },
      { startHour: 11, endHour: 16, type: 'maintenance', label: 'Sunday Mega Block Window' },
      { startHour: 16, endHour: 21.5, type: 'train-occupied' },
      { startHour: 21.5, endHour: 24, type: 'available' },
    ],
  },
  {
    id: 'COR-CSMT-KYN',
    name: 'CSMT–KYN',
    from: 'CSMT',
    to: 'Kalyan (Central Main Line)',
    totalKm: 54.0,
    availableHours: 4.0,
    trainDensity: 'High',
    plannedBlocks: 0,
    availableCapacity: 70,
    risk: 'High',
    timeSlots: [
      { startHour: 0, endHour: 4, type: 'available' },
      { startHour: 4, endHour: 11, type: 'train-occupied' },
      { startHour: 11, endHour: 16, type: 'maintenance', label: 'Main Line Mega Block' },
      { startHour: 16, endHour: 22, type: 'train-occupied' },
      { startHour: 22, endHour: 24, type: 'available' },
    ],
  },
  {
    id: 'COR-CSMT-PNVL',
    name: 'CSMT–PNVL',
    from: 'CSMT',
    to: 'Panvel (Harbour Line)',
    totalKm: 49.0,
    availableHours: 5.2,
    trainDensity: 'High',
    plannedBlocks: 0,
    availableCapacity: 78,
    risk: 'High',
    timeSlots: [
      { startHour: 0, endHour: 4, type: 'available' },
      { startHour: 4, endHour: 11, type: 'train-occupied' },
      { startHour: 11, endHour: 16, type: 'maintenance', label: 'Harbour Line Mega Block' },
      { startHour: 16, endHour: 22, type: 'train-occupied' },
      { startHour: 22, endHour: 24, type: 'available' },
    ],
  },
];

// Zero Dummy Data Arrays — Tasks, Blocks, Conflicts, and Recommendations are strictly populated live
export const maintenanceTasksData = [];
export const maintenanceBlocksData = [];
export const conflictsData = [];
export const aiRecommendationsData = [];

export const systemIntegrationsData = [
  {
    id: 'SYS-CR-TMS',
    name: 'CR-TMS',
    fullName: 'Central Railway Track Management System',
    department: 'Engineering (Track)',
    endpoint: 'api.cr.tms.indianrail.gov.in/mumbai-suburban/defects',
    status: 'Connected',
    lastSync: '30 Aug 2026 · 01:25',
    recordsCount: 0,
    description: 'Ultrasonic track defect logs, turnout wear, ballast profiles for Mumbai Suburban division',
  },
  {
    id: 'SYS-CR-SMMS',
    name: 'CR-SMMS',
    fullName: 'Central Railway Signal & Telecom Management',
    department: 'S&T',
    endpoint: 'api.cr.smms.indianrail.gov.in/suburban-axle-counters',
    status: 'Connected',
    lastSync: '30 Aug 2026 · 01:25',
    recordsCount: 0,
    description: 'Digital Axle Counters, point machine health logs, automatic signal logs for Trans-Harbour line',
  },
  {
    id: 'SYS-CR-TDMS',
    name: 'CR-TDMS',
    fullName: 'Central Railway Traction Distribution Management',
    department: 'Traction OHE',
    endpoint: 'api.cr.tdms.indianrail.gov.in/ohe-substations',
    status: 'Connected',
    lastSync: '30 Aug 2026 · 01:25',
    recordsCount: 0,
    description: '25kV AC / 1500V DC OHE catenary inspections, insulator wash logs, TSS power feeds',
  },
  {
    id: 'SYS-CR-COA',
    name: 'Mumbai COA',
    fullName: 'Mumbai Suburban Control Office Application',
    department: 'Suburban Traffic Control',
    endpoint: 'api.cr.coa.indianrail.gov.in/suburban-timetable',
    status: 'Connected',
    lastSync: '30 Aug 2026 · 01:25',
    recordsCount: 0,
    description: 'Suburban timetable, local train GPS tracking, Sunday Mega Block bulletins',
  },
];
